# Generated by Django 4.0.4 on 2022-06-04 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slice', '0002_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=15)),
                ('is_veg', models.BooleanField(default=True)),
                ('price', models.IntegerField()),
                ('menuImage', models.ImageField(default='', upload_to='menuImages/')),
            ],
        ),
        migrations.RemoveField(
            model_name='restourant_menu',
            name='restourant_id',
        ),
        migrations.RenameModel(
            old_name='order_details',
            new_name='OrderDetails',
        ),
        migrations.RenameModel(
            old_name='restourant',
            new_name='Restaurant',
        ),
        migrations.DeleteModel(
            name='profile',
        ),
        migrations.DeleteModel(
            name='restourant_menu',
        ),
        migrations.AddField(
            model_name='restaurantmenu',
            name='restaurantId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RestaurantId', to='slice.restaurant'),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='food_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_id', to='slice.restaurantmenu'),
        ),
    ]
