# Generated by Django 4.0.4 on 2022-06-04 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slice', '0003_restaurantmenu_remove_restourant_menu_restourant_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='email',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='phoneNumber',
            field=models.CharField(default='', max_length=100),
        ),
    ]
